name: Fetch Static GTFS Data
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./Scripts
      run: swift FetchStaticData.swift

    - name: Print output
      working-directory: ./Scripts
      run: more Trips.csv

    - name: Upload to R2
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        command: r2 object put choochoo/Trips.csv --file=./Scripts/Trips.csv
